<?php

namespace FrontBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

    function findFeedbyEvent($id){
        $query=$this->getEntityManager()
            ->createQuery("select c from FrontBundle:Commentaire c WHERE c.idArticle LIKE :id")
                ->setParameter('id','%'.$id.'%');
        return $query->getResult();
    }

}
