<?php

namespace FrontBundle\Repository;

/**
 * likedislikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likedislikeRepository extends \Doctrine\ORM\EntityRepository
{

    function findLikeDislike($u,$a)
    {
        $query=$this->getEntityManager()->createQuery(
            "select m.id from FrontBundle:likedislike m WHERE  m.id_user = $u and m.id_Article = $a"
        );
        return $query->getSingleScalarResult();
    }


    function findLikeDislike2($u,$a)
    {
        $query=$this->getEntityManager()->createQuery(
            "select m from FrontBundle:likedislike m WHERE  m.id_user = $u and m.id_Article = $a"
        );
        return $query->getResult();
    }

}
