<?php

namespace FrontBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    function findProduitParCosmetique(){
        $query=$this->getEntityManager()
            ->createQuery("select c from FrontBundle:Produit c  WHERE c.type LIKE 'Cosmitique'") ;

        return $query->getResult();
    }


    function findProduitParAccesoire(){
        $query=$this->getEntityManager()
            ->createQuery("select c from FrontBundle:Produit c  WHERE c.type LIKE 'Accesoires'") ;

        return $query->getResult();
    }


    function findProduitParAlimentaire(){
        $query=$this->getEntityManager()
            ->createQuery("select c from FrontBundle:Produit c  WHERE c.type LIKE 'Alimentaire'") ;

        return $query->getResult();
    }


}
