<?php
/**
 * Created by PhpStorm.
 * User: Black hummer
 * Date: 28/11/2019
 * Time: 23:36
 */

namespace FrontBundle\Repository;
/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

}