<?php
/**
 * Created by PhpStorm.
 * User: Black hummer
 * Date: 28/11/2019
 * Time: 23:34
 */

namespace FrontBundle\Repository;

/**
 * VeterinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class VeterinaireRepository extends \Doctrine\ORM\EntityRepository
{

}