# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_VETERINAIRE: [ROLE_VETERINAIRE,ROLE_CLIENT]

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login

            anonymous:    true
            logout:
                target:   /login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~



#    access_denied_url: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }


        - { path: ^/front, role: ROLE_CLIENT }
        - { path: ^/front, role: ROLE_VETERINAIRE }
        - { path: ^/back, role: ROLE_SUPER_ADMIN }




#        - { path: ^/back, role: ROLE_VETERINAIRE }




#        - { path: ^/front/produit_edit, role: ROLE_SUPER_ADMIN }
#        - { path: ^/front/produit_delete, role: ROLE_SUPER_ADMIN }
#        -
#
#        - { path: ^/front/evenement_new, role: ROLE_SUPER_ADMIN }
#        - { path: ^/front/evenement_edit, role: ROLE_SUPER_ADMIN }
#        - { path: ^/front/evenement_delete, role: ROLE_SUPER_ADMIN }
#
#        - { path: ^/front/article_delete, role: ROLE_VETERINAIRE }
#        - { path: ^/front/article_edit, role: ROLE_VETERINAIRE }
