<?php
/**
 * Created by PhpStorm.
 * User: Black hummer
 * Date: 28/11/2019
 * Time: 23:35
 */

namespace FrontBundle\Repository;
/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class FeedRepository extends \Doctrine\ORM\EntityRepository
{

}